### ISSUE TITLE
IDE doesn't open new file when pressing Crtl+Shift+G

### ISSUE THREAD

**Issue by bien6mui** [lintingbin2009/sublime_erl#2]
Hi again @lintingbin2009 ,

I see one issue when i press Crtl+Shift+G, that is the content of function is still displayed but it doesn't open that new file (that file is containing the function), it just display in current parent file. So I think it will be better if when we press Crtl+Shift+G, then it will open the new file in IDE (the same as the case we move mouse to a function a click into "goto_definition(erlang)") :p 

Thanks.

**Comment by lintingbin** [comment]
I have fixed this problem in the 1.0.9 version. You can test it in your PC.

**Comment by bien6mui** [comment]
I think the issue is still not works in my project after applying 1.0.9 version, I am not sure that I and you had a little bit misunderstanding there, so let me explain my case one more times :p 

I have two erlang file: file_1.erl and file_2.erl. 

**file_1.erl** call to a function with name:  **file_2:function_2**. But if **file_2.erl** was not still opened on the "Tabs" then when we press Ctrl+Shift+G at **file_2:function_2** , the content of **function_2** still displayed but not in a new "Tabs" with **file_2.erl**, it just displayed inside **file_1.erl** 

This issue just come from keymap "Ctrl+Shift+G", for mousemap (goto_definition(erlang)) it has still worked well now 

That is my issue, so please help me to check it again. Thank you so much @lintingbin2009 :)

**Comment by bien6mui** [comment]
hi @lintingbin2009 it works well now, really thank you :))
